org: shehbaj
app: polysrubs-scraper
service: polyscrubs-scraper-cron-job

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  environment:
    DB_NAME: ${env:DB_NAME}
    TBL_NAME: ${env:TBL_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - timestream:*
      Resource: "*"


custom:
  pythonRequirements:
    pythonBin: python3

functions:
  cronHandler:
    handler: client.handler
    timeout: 120
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/30 * ? * MON-SUN *)

